server:
  port: 8001


#mybatis 配置
mybatis:
  mapper-location: classpath*:sqlMapper/*.xml
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#      map-underscore-to-camel-case: true

spring:
  # 数据源配置：
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/pathdemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      validation-query-timeout: 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 10000
          enabled: true
        wall:
          enabled: true
          db-type: mysql
      filters: stat,wall,slf4j
  # 邮箱服务配置：
  mail:
    host: smtp.qq.com
    username: thj.666@qq.com
    password: yonsbtvmtlwsdcha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 587

